import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "/styles/globals.css";
import localFont from "next/font/local";

const ltSuperior = localFont({
  src: [
    {
      path: "./fonts/LTSuperior/LTSuperior-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/LTSuperior/LTSuperior-ThinItalic.ttf",
      weight: "100",
      style: "italic",
    },
    {
      path: "./fonts/LTSuperior/LTSuperior-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/LTSuperior/LTSuperior-LightItalic.ttf",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/LTSuperior/LTSuperior-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/LTSuperior/LTSuperior-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/LTSuperior/LTSuperior-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/LTSuperior/LTSuperior-MediumItalic.ttf",
      weight: "500",
      style: "italic",
    },
    {
      path: "./fonts/LTSuperior/LTSuperior-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/LTSuperior/LTSuperior-SemiBoldItalic.ttf",
      weight: "600",
      style: "italic",
    },
    {
      path: "./fonts/LTSuperior/LTSuperior-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/LTSuperior/LTSuperior-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/LTSuperior/LTSuperior-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/LTSuperior/LTSuperior-ExtraBoldItalic.ttf",
      weight: "800",
      style: "italic",
    },
    {
      path: "./fonts/LTSuperior/LTSuperior-Black.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/LTSuperior/LTSuperior-BlackItalic.ttf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-ltsuperior",
  display: "swap",
});

export const messina = localFont({
  src: [
    {
      path: "./fonts/Messina/MessinaSerif-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Messina/MessinaSerif-LightItalic.ttf",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/Messina/MessinaSerif-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Messina/MessinaSerif-RegularItalic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/Messina/MessinaSerif-Book.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Messina/MessinaSerif-BookItalic.ttf",
      weight: "500",
      style: "italic",
    },
    {
      path: "./fonts/Messina/MessinaSerif-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Messina/MessinaSerif-SemiBoldItalic.ttf",
      weight: "600",
      style: "italic",
    },
    {
      path: "./fonts/Messina/MessinaSerif-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Messina/MessinaSerif-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-messina",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ltSuperior.variable} ${messina.variable} scroll-smooth`}>
      <body
        className={`antialiased overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  ); 
}
